"""SCW run attestation builder (architecture decision D7).

One run -> one attestation. run_id is locally derivable, no RNG:
  run-<UTC compact>-<first 8 hex of input_sha256>
The reviewer_signoff block is schema-const blank; this builder has no code
path that can populate it (A8). Only the CSV hash embeds (D9); JSON/HTML
hashes are post-hoc receipt data.
"""
from .canonical import sha
from .engine import VERDICTS

ATTESTATION_VERSION = "1.0.0"

# Locked disclaimer, byte-identical to the golden attestation fixtures
# (fixtures/run-attestation-*.fixture.json). Verbatim, never translated.
DISCLAIMER = {
    "en": ("This workbook is a drafting aid. Its verdicts are proposed "
           "worksheet fields generated by a deterministic rule pack; they "
           "are not a sharia ruling, not a legal opinion, and not an "
           "approval. A qualified human reviewer must complete the sign-off "
           "block before any use."),
    "ar": ("هذا الدفتر أداة مسودة. الأحكام فيه حقول مقترحة ينتجها رتبة "
           "قواعد حتمية؛ وليست فتوى ولا رأيا قانونيا ولا موافقة. يجب أن "
           "يكمل المراجع البشري المؤهل خانة التوقيع قبل أي استخدام."),
}

BLANK_SIGNOFF = {"reviewer_name": "", "reviewer_role": "", "review_date": "",
                 "statement": None, "completed": False}


def compact_utc(ts):
    """2026-09-22T22:10:00Z -> 20260922T221000Z (V4d formula)."""
    return ts.replace("-", "").replace(":", "")


def build_attestation(case_input, case_result, pack_sha, run_started_utc,
                      run_finished_utc, csv_filename, csv_sha256,
                      engine_version):
    input_sha = sha(case_input)
    results_sha = sha(case_result)
    run_id = "run-%s-%s" % (compact_utc(run_started_utc), input_sha[:8])
    counts = {k: 0 for k in VERDICTS}
    for item in case_result["items"]:
        counts[item["verdict_proposed"]] += 1
    rp = case_result["rule_pack"]
    return {
        "attestation_version": ATTESTATION_VERSION,
        "run_id": run_id,
        "clock_source": "local",
        "run_started_utc": run_started_utc,
        "run_finished_utc": run_finished_utc,
        "offline_assertion": {"network_calls_made": False,
                              "engine_is_deterministic": True,
                              "llm_invoked": False},
        "input_id": case_input["input_id"],
        "input_sha256": input_sha,
        "rule_pack": {"pack_id": rp["pack_id"],
                      "pack_version": rp["pack_version"],
                      "sha256": pack_sha, "status": rp["status"]},
        "engine_version": engine_version,
        "results_sha256": results_sha,
        "verdict_counts": counts,
        "exports": [{"kind": "csv", "filename": csv_filename,
                     "sha256": csv_sha256}],
        "reviewer_signoff": dict(BLANK_SIGNOFF),
        "disclaimer": dict(DISCLAIMER),
    }
